// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqgjbimdhgqsksdblejz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZ2piaW1kaGdxc2tzZGJsZWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjAyMzMsImV4cCI6MjA2NDMzNjIzM30.--JJVoWrYCoVsYzQW00Lq6HJUzAHFliYNDLDL5Beg7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);